databases:
  - name: root
    databaseName: crmagic
    user: localhost

services:
  - type: web
    name: crmagic
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Crmagic.wsgi.application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: root
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4